# Generated by Django 4.1.3 on 2023-08-11 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_alter_game_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('selecting_active_user', 'selecting active user'), ('selecting_question', 'selecting question'), ('showing_question', 'showing question'), ('cat_in_a_bag', 'cat in a bag'), ('rate_question', 'rate question'), ('answering', 'answering')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_player_count',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('is_responder', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='game', to='game.player'),
        ),
    ]
