# Generated by Django 4.1.3 on 2023-08-27 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_game_active_round_game_is_paused_game_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('SELECTING_ACTIVE_USER', 'Selecting Active User'), ('SELECTING_QUESTION', 'Selecting Question'), ('SHOWING_QUESTION', 'Showing Question'), ('CAT_IN_A_BAG', 'Cat in a Bag'), ('RATE_QUESTION', 'Rate Question'), ('ANSWERING', 'Answering'), ('FINAL', 'Final')], max_length=50),
        ),
    ]
