# Generated by Django 4.1.3 on 2023-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_active_question_alter_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
